-- cursor--
DECLARE

ENO EMP.EMPNO%TYPE;
ENM EMP.ENAME%TYPE;
BEGIN
  
SELECT EMPNO,ENAME INTO ENO,ENM FROM EMP WHERE EMPNO=7839;
DBMS_OUTPUT.put_line('EMPNO '||ENO||' EMPNAME '||ENM);
END;

SELECT * FROM EMP;
SELECT * FROM DEPT;

--2--

DECLARE

VNAME EMP.ENAME%TYPE;
VJOB EMP.JOB%TYPE;

CURSOR CUR_EMPLIST
IS
SELECT ENAME,JOB FROM EMP;
BEGIN
  OPEN CUR_EMPLIST;
  LOOP
    FETCH CUR_EMPLIST INTO VNAME,VJOB;
    EXIT WHEN CUR_EMPLIST%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(VNAME|| ' JOB ROLE IS '|| VJOB);
    END LOOP;
    DBMS_OUTPUT.put_line('NO OF RECORDS '||CUR_EMPLIST%ROWCOUNT);
    CLOSE CUR_EMPLIST;
    END;
    
---3--

SELECT ENAME,DNAME  FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

DECLARE

ENM EMP.ENAME%TYPE;
DNM DEPT.DNAME%TYPE;

CURSOR CUR_LIST
IS
SELECT ENAME,DNAME INTO ENM,DNM FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DEPTNO;
BEGIN
OPEN CUR_LIST;
LOOP
  FETCH CUR_LIST INTO ENM,DNM;
  EXIT WHEN CUR_LIST%NOTFOUND;
DBMS_OUTPUT.put_line('EMPNAME '||ENM||' DNAME '||DNM);
END LOOP;
DBMS_OUTPUT.PUT_LINE('NO OF RECORDS '||CUR_LIST%ROWCOUNT);
    CLOSE CUR_LIST;
    END;
    
--4--
SELECT DNAME ,COUNT(EMPNO) FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DEPTNO GROUP BY DNAME HAVING COUNT(EMPNO)>=2; ;

DECLARE
DNM DEPT.DNAME%TYPE;
EC EMP.EMPNO%TYPE;

CURSOR CUR_LIST
IS
SELECT DNAME ,COUNT(EMPNO) INTO DNM,EC FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DEPTNO GROUP BY DNAME HAVING COUNT(EMPNO)>=2;
BEGIN
OPEN CUR_LIST;
LOOP
  FETCH CUR_LIST INTO DNM,EC;
  EXIT WHEN CUR_LIST%NOTFOUND;
DBMS_OUTPUT.put_line('DNAME '||DNM||' EMPNO '||EC);
END LOOP;
DBMS_OUTPUT.PUT_LINE('NO OF RECORDS '||CUR_LIST%ROWCOUNT);
    CLOSE CUR_LIST;
    END; 
    
--parameterized-- 

DECLARE

VNAME EMP.ENAME%TYPE;
VJOB EMP.JOB%TYPE;

CURSOR CUR_EMPLIST(PRM_DEPTNO NUMBER) IS

SELECT ENAME,JOB  FROM EMP WHERE DEPTNO=PRM_DEPTNO;
BEGIN
  OPEN CUR_EMPLIST(10);
  LOOP
    FETCH CUR_EMPLIST INTO VNAME,VJOB;
    EXIT WHEN CUR_EMPLIST%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(VNAME|| ' JOB ROLE IS '|| VJOB);
    END LOOP;
    DBMS_OUTPUT.put_line('NO OF RECORDS '||CUR_EMPLIST%ROWCOUNT);
    CLOSE CUR_EMPLIST;
    END;
--REF CURSROR--

DECLARE
TYPE REF_CUR_EMP IS REF CURSOR;
EMPD_LIST REF_CUR_EMP;

VNAME EMP.ENAME%TYPE;
VSAL EMP.SAL%TYPE;
VDNAME DEPT.DNAME%TYPE;
VLOC DEPT.LOC%TYPE;

BEGIN
  OPEN EMPD_LIST FOR SELECT ENAME,SAL FROM EMP;
  DBMS_OUTPUT.PUT_LINE('LIST OF EMPLOYEES');
  DBMS_OUTPUT.PUT_LINE('------------------');
  LOOP
    FETCH EMPD_LIST INTO VNAME,VSAL;
    EXIT WHEN EMPD_LIST%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('NAME OF EMPLOYEE '||VNAME||'  AND SALARY '||VSAL);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('-----------------------------');
    CLOSE EMPD_LIST;
    
    
    OPEN EMPD_LIST FOR SELECT DNAME,LOC FROM DEPT;
  DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME AND LOCATION');
  DBMS_OUTPUT.PUT_LINE('-----------------------------');
  LOOP
    FETCH EMPD_LIST INTO VDNAME,VLOC;
    EXIT WHEN EMPD_LIST%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('NAME OF DEPARTMENT '||VDNAME||'  AND LOCATION '||VLOC);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('-----------------------------');
    CLOSE EMPD_LIST;
    END;
    
 --WEAK TYPE OF REF--
 
 DECLARE 
 
 TYPE REF_CUR_DEPT IS REF CURSOR RETURN DEPT%ROWTYPE;
 
 DEPT_LIST REF_CUR_DEPT;
 VDEP_ROW DEPT%ROWTYPE;
 
 BEGIN
   OPEN DEPT_LIST FOR SELECT * FROM DEPT;
   DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME LIST');
   DBMS_OUTPUT.PUT_LINE('-------------------------');
   LOOP
     FETCH DEPT_LIST INTO VDEP_ROW;
     EXIT WHEN DEPT_LIST%NOTFOUND;
     DBMS_OUTPUT.PUT_LINE('DEPARTMENT NO '||VDEP_ROW.DEPTNO);
        DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME '||VDEP_ROW.DNAME);
           DBMS_OUTPUT.PUT_LINE('DEPARTMENT LOCATION '||VDEP_ROW.LOC);
              DBMS_OUTPUT.PUT_LINE('-------------------------');
              END LOOP;
              CLOSE DEPT_LIST;
              END;

     
    
    
