-----------------PACKAGES-------------------------------

--CREATE A PROCEDURE TO ADD RECORD IN DEPT----
         
       ---DECLARE----
CREATE OR REPLACE PACKAGE DEP_PACK
IS
V_BONUSRATE NUMBER :=0.10;
PROCEDURE ADD_RECORDS(P_DEPTNO IN NUMBER,P_DNAME IN VARCHAR2,P_LOC IN VARCHAR2);
 FUNCTION CAL_BONUS(P_SAL IN NUMBER)RETURN NUMBER;
 END DEP_PACK;
 
        ---BODY----
CREATE OR REPLACE PACKAGE BODY DEP_PACK
IS
PROCEDURE ADD_RECORDS(P_DEPTNO IN NUMBER,P_DNAME IN VARCHAR2,P_LOC IN VARCHAR2)
  IS
  BEGIN
    INSERT INTO DEPT (DEPTNO,DNAME,LOC) VALUES(P_DEPTNO,P_DNAME,P_LOC);
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT'||P_DNAME||'SUCCESSFULLY');
    END ADD_RECORDS ;
    
    --CALL--
    
FUNCTION CAL_BONUS(P_SAL IN NUMBER) RETURN NUMBER
  IS BONUS NUMBER;
  BEGIN
    BONUS :=P_SAL * V_BONUSRATE;
    RETURN BONUS;
    END CAL_BONUS;
     END DEP_PACK;

      
 ---CALLING PROCEDURE--
 
 BEGIN
   DEP_PACK.ADD_RECORDS(47,'MARKETING','KERALA');
   END;

   
   ----
   
   SELECT ENAME,DEP_PACK.CAL_BONUS(SAL)AS BONUS FROM EMP;

SELECT * FROM DEPT WHERE DEPTNO=19;

------------------------------------------------------

----------------------RECORDS------------

------1.TABLE BASED------------

DECLARE
V_EMP EMP%ROWTYPE;
BEGIN
  SELECT * INTO V_EMP FROM EMP WHERE EMPNO=7839;
  DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME '||V_EMP.ENAME);
  DBMS_OUTPUT.PUT_LINE('JOB ROLE '||V_EMP.JOB);
  END;

-------2.CURSOR-----

DECLARE CURSOR EMP_CUR
IS
SELECT EMPNO,ENAME ,SAL FROM EMP;
EMP_REC EMP_CUR%ROWTYPE;
BEGIN
  OPEN EMP_CUR;
  LOOP
    FETCH EMP_CUR INTO EMP_REC;
    EXIT WHEN EMP_CUR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(EMP_REC.EMPNO||' '||EMP_REC.ENAME||' '||EMP_REC.SAL);
    END LOOP;
    END;
-----3.USER DEFINED-----

DECLARE 
TYPE MYREC_TYPE IS RECORD(STUDENT_NAME VARCHAR2(20),AGE NUMBER);
MY_REC MYREC_TYPE;
BEGIN
  MY_REC.STUDENT_NAME :='ANJITHA RAJ';
  MY_REC.AGE:=25;
  DBMS_OUTPUT.PUT_LINE(MY_REC.STUDENT_NAME||' '||MY_REC.AGE);
  END;
--------4.USER DEFINED(TABLE)---

DECLARE
TYPE MY_REC IS RECORD(RNAME VARCHAR2(20),RSAL NUMBER);
EMP_REC MY_REC;
BEGIN
  SELECT ENAME,SAL INTO EMP_REC FROM EMP WHERE EMPNO=7839;
  DBMS_OUTPUT.PUT_LINE(EMP_REC.RNAME||' '||EMP_REC.RSAL);
  END;


