-----------------PACKAGES-------------------------------

--CREATE A PROCEDURE TO ADD RECORD IN DEPT----
         
       ---DECLARE----
CREATE OR REPLACE PACKAGE DEP_PACK
IS
V_BONUSRATE NUMBER:=0.10;
PROCEDURE ADD_RECORDS(P_DEPTNO IN NUMBER,P_DNAME IN VARCHAR2,P_LOC IN VARCHAR2);
 FUNCTION CAL_BONUS(P_SAL IN NUMBER)RETURN NUMBER;
 END DEP_PACK;
 
        ---BODY----
CREATE OR REPLACE PACKAGE BODY DEP_PACK
IS
PROCEDURE ADD_RECORDS(P_DEPTNO IN NUMBER,P_DNAME IN VARCHAR2,P_LOC IN VARCHAR2)
  IS
  BEGIN
    INSERT INTO DEPT (DEPTNO,DNAME,LOC) VALUES(P_DEPTNO,P_DNAME,P_LOC);
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT'||P_DNAME||'SUCCESSFULLY');
    END ADD_RECORDS ;
    
    --CALL--
    
FUNCTION CAL_BONUS(P_SAL IN NUMBER) RETURN NUMBER
  AS BONUS NUMBER;
  BEGIN
    BONUS:=P_SAL * V_BONUSRATE;
    RETURN BONUS;
    END CAL_BONUS;
     END DEP_PACK;

      
 ---CALLING PROCEDURE--
 
 BEGIN
   DEP_PACK.ADD_RECORDS(19,'MARKETING','KERALA');
   END;

   
   ----
   
   SELECT DNAME,DEP_PACK.CAL_BONUS(SAL)AS BONUS FROM DEPT;

SELECT * FROM DEPT WHERE DEPTNO=19;
SHOW ERRORS PACKAGE DEP_PACK;
SHOW ERRORS PACKAGE BODY DEP_PACK;
------------------------------------------------------

CREATE OR REPLACE PACKAGE DEP_PACK IS
  V_BONUSRATE NUMBER := 0.10;

  PROCEDURE ADD_RECORDS(
    P_DEPTNO IN NUMBER,
    P_DNAME  IN VARCHAR2,
    P_LOC    IN VARCHAR2
  );

  FUNCTION CAL_BONUS(P_SAL IN NUMBER) RETURN NUMBER;
END DEP_PACK;
/
CREATE OR REPLACE PACKAGE BODY DEP_PACK IS

  PROCEDURE ADD_RECORDS(
    P_DEPTNO IN NUMBER,
    P_DNAME  IN VARCHAR2,
    P_LOC    IN VARCHAR2
  ) IS
  BEGIN
    INSERT INTO DEPT (DEPTNO, DNAME, LOC)
    VALUES (P_DEPTNO, P_DNAME, P_LOC);

    DBMS_OUTPUT.PUT_LINE('DEPARTMENT ' || P_DNAME || ' ADDED SUCCESSFULLY');
  END ADD_RECORDS;

  FUNCTION CAL_BONUS(P_SAL IN NUMBER) RETURN NUMBER IS
    BONUS NUMBER;
  BEGIN
    BONUS := P_SAL * V_BONUSRATE;
    RETURN BONUS;
  END CAL_BONUS;

END DEP_PACK;
/
DECLARE
  V_BONUS NUMBER;
BEGIN
  V_BONUS := DEP_PACK.CAL_BONUS(50000);
  DBMS_OUTPUT.PUT_LINE('Calculated Bonus: ' || V_BONUS);
END;
/ BEGIN
   DEP_PACK.ADD_RECORDS(19,'MARKETING','KERALA');
   END;
