------------------TRANSACTION---------------------
--1.INSERT--
CREATE OR REPLACE PROCEDURE PRO_TRANS
IS PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
INSERT INTO DEPT VALUES(57,'GFTN','KOCHI');
INSERT INTO DEPT VALUES(97,'HJFHJ','KOTTAYAM');
SAVEPOINT PROCSS;
INSERT INTO DEPT VALUES(79,'KHGYU','KOLLAM');
ROLLBACK TO PROCSS;
COMMIT;
END;

BEGIN
  PRO_TRANS;
  END;
  
SELECT * FROM DEPT;

--MULTIPLE COLUMS---

DECLARE 
TYPE T_RECD IS RECORD(VNAME VARCHAR2(35),VSALARY NUMBER,VDEPTNO NUMBER);
TYPE T_TABB IS TABLE OF T_RECD;
T_EMPT T_TABB;
BEGIN
  SELECT ENAME,SAL ,DEPTNO BULK COLLECT INTO T_EMPT FROM EMP;
  DBMS_OUTPUT.PUT_LINE('EMPLOYEE DATA');
  DBMS_OUTPUT.PUT_LINE('----------------');
  FOR I IN T_EMPT.FIRST..T_EMPT.LAST
    LOOP
      DBMS_OUTPUT.PUT_LINE(T_EMPT(I).VNAME||' WITH A SALARY OF '||T_EMPT(I).VSALARY||' WORKS IN DEPT '
      ||T_EMPT(I).VDEPTNO);
      END LOOP;
      END;
      
---COLLECT LIMIT---

DECLARE 
C_LIMIT CONSTANT PLS_INTEGER DEFAULT 3;
CURSOR EMP_CUR IS SELECT * FROM EMP;
TYPE EMP_EB IS TABLE OF EMP%ROWTYPE INDEX BY BINARY_INTEGER;
EMP_T EMP_EB;
BEGIN
  OPEN EMP_CUR;
  LOOP
    FETCH EMP_CUR BULK COLLECT INTO EMP_T LIMIT C_LIMIT;
    EXIT WHEN EMP_T.COUNT=0;
    DBMS_OUTPUT.PUT_LINE('RETREIVED ROWS '||EMP_T.COUNT);
    FOR I IN 1..EMP_T.COUNT
    LOOP
      DBMS_OUTPUT.PUT_LINE(EMP_T(I).EMPNO||' - '||EMP_T(I).ENAME);
      END LOOP;
      END LOOP;
      CLOSE EMP_CUR;
      END;
-----------------dynamic sql----------

CREATE OR REPLACE PROCEDURE UPD_DYNAMIC(P_TABLE VARCHAR2,P_COLUMN VARCHAR2,N_VALUE VARCHAR2,P_CONDT VARCHAR2)
AS
V_SQL VARCHAR2(1000);
BEGIN
  V_SQL :='UPDATE '||P_TABLE||' SET '||P_COLUMN||'=:1'||'WHERE '||P_CONDT;
  EXECUTE IMMEDIATE V_SQL USING N_VALUE;
  DBMS_OUTPUT.PUT_LINE('UPDATED ...'||V_SQL);
  END;
  
  BEGIN
    UPD_DYNAMIC('DEPT','LOC','HUSTON','DEPTNO=96');
    END;
    
    SELECT * FROM DEPT;
